### PR TITLE
Fixed Updates for clean merge

### PR DESCRIPTION
**Pull request by MrM0bius**
Took your advice and opened a branch then made my commits one feature at a time.  Think I'm catching on to the process now.

Same set of updates, with tidier skybox export code.

### CODE REVIEW

**Comment by MrM0bius** [comment]
I'd like you to test on Linux before I merge

**Comment by void4** [comment]
Done! Everything seems to work on my machine. Merged :)
* It's best to just use one commit per feature, even if it affects multiple files. This way, the project is always in a "working" state and ready to use after every single commit.
* We should probably indicate the latest supported version (and minimal version requirements) in the README. 
* Although I would like to encourage users to use IPFS, the decision to enable it by default should be delayed until a more non-power-user friendly installation interface is created.
* Should we have more users in the future it would be nice to get some more feedback on their favourite preferences. Right now, r/JanusVR is probably the best channel for this.

**Comment by MrM0bius** [comment]
I agree about IPFS, though it's a great feature.  I'm also thinking about doing an ftp uploader for those of us who publish the old fashioned way.

Asset scripts and shaders should be easy to implement in basically the same way as the skybox, so I'll probably add those in soon.  (eventually it would be cool to somehow preview glsl shaders and skybox in blender).

Persistent paths for export folder and janus exe would be nice, kind of a pain reentering them every time you start, and we're already safe from overwriting with the generated subfolders.

**Comment by void4** [comment]
JanusVR could also support accessing local, nonhosted files, this would solve all kinds of issues when testing (updating files, no cached hosted files etc.). Persistent path preferences should be possible to implement through the bpy.types.AddonPreferences class (which already exists in the source - I didn't get it to work yet, though).

**Comment by MrM0bius** [comment]
I'm not sure I understand what you mean.  Doesn't Janus already support
accessing local files?  That's how the export launcher works if IPFS is
disabled, it just points to the local exported index.html.

**Comment by void4** [comment]
I thought this was not supported on Linux - the reason for it not working was that the path was manually joined with a backslash (now, os.path.join() is used).

**Comment by MrM0bius** [comment]
oops, yeah that makes sense

**Pull request merged**
